# Generated by Django 4.0.5 on 2022-06-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('employee_id', models.IntegerField(default=0)),
                ('department', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('bonus', models.IntegerField()),
                ('phone_number', models.IntegerField()),
                ('email_id', models.EmailField(max_length=100)),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
